excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- tools

cyclomatic_complexity:
    warning: 15
    error: 25

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true